// types generated by typechain/truffle-v5
require("dotenv").config()
const Katie = artifacts.require('Katie');
import { assert } from "chai"
require("chai").use(require("chai-as-promised")).should();

contract("Katie", (accounts) => {
  let katie;

  before(async () => {
    katie = await Katie.deployed();
  })

  describe("deployment", async () => {
    it("deploys successfully", async () => {
      const address = katie.address;
      console.log(address);
      assert.notEqual(address, "");
      assert.notEqual(address, 0x0);
      assert.notEqual(address, null);
    });

    it("has a name", async () => {
      const name = await katie.name();
      assert.equal(name, "Katie");
    });

    it("has a symbol", async () => {
      const name = await katie.symbol();
      assert.equal(name, "KATE");
    });
  });
})